const ExcelJS = require('exceljs');

async function generateExcel(timesheet) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'SiteView — Build Chain';

  const sheet = workbook.addWorksheet('Timesheet');

  // Header styling
  const headerFill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1A237E' } };
  const headerFont = { color: { argb: 'FFFFFFFF' }, bold: true };

  // Title
  sheet.mergeCells('A1:F1');
  sheet.getCell('A1').value = 'BUILD CHAIN — SITE VIEW TIMESHEET';
  sheet.getCell('A1').font = { bold: true, size: 14, color: { argb: 'FF1A237E' } };
  sheet.getCell('A1').alignment = { horizontal: 'center' };

  // Employee Info
  sheet.getCell('A3').value = 'Employee:';
  sheet.getCell('B3').value = timesheet.employeeName;
  sheet.getCell('A4').value = 'Site:';
  sheet.getCell('B4').value = timesheet.siteId;
  sheet.getCell('A5').value = 'Payment Type:';
  sheet.getCell('B5').value = timesheet.paymentType;
  sheet.getCell('A6').value = 'Period:';
  sheet.getCell('B6').value = `${timesheet.startDate} to ${timesheet.endDate}`;

  // Summary
  sheet.getCell('A8').value = 'SUMMARY';
  sheet.getCell('A8').font = { bold: true };
  sheet.getCell('A9').value = 'Total Hours';
  sheet.getCell('B9').value = timesheet.totalHours;
  sheet.getCell('A10').value = 'Break Hours';
  sheet.getCell('B10').value = timesheet.breakHours;
  sheet.getCell('A11').value = 'Billable Hours';
  sheet.getCell('B11').value = timesheet.billableHours;
  sheet.getCell('A12').value = 'Total Pay';
  sheet.getCell('B12').value = timesheet.payAmount;
  sheet.getCell('B12').numFmt = '$#,##0.00';

  // Daily Breakdown Header
  const headerRow = sheet.getRow(15);
  ['Date', 'Total Hours', 'Break Hours', 'Billable Hours', 'Punch In', 'Punch Out'].forEach((h, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = h;
    cell.fill = headerFill;
    cell.font = headerFont;
    cell.alignment = { horizontal: 'center' };
  });

  // Daily Breakdown Data
  if (timesheet.dailyBreakdown) {
    timesheet.dailyBreakdown.forEach((day, idx) => {
      const row = sheet.getRow(16 + idx);
      row.getCell(1).value = day.date;
      row.getCell(2).value = day.totalHours;
      row.getCell(3).value = day.breakHours;
      row.getCell(4).value = day.billableHours;

      const punchIn = day.punches?.find(p => p.type === 'in');
      const punchOut = day.punches?.find(p => p.type === 'out');
      row.getCell(5).value = punchIn ? new Date(punchIn.timestamp).toLocaleTimeString() : '-';
      row.getCell(6).value = punchOut ? new Date(punchOut.timestamp).toLocaleTimeString() : '-';

      if (idx % 2 === 0) {
        row.eachCell(cell => {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F5F5' } };
        });
      }
    });
  }

  // Column widths
  sheet.columns = [
    { width: 15 }, { width: 15 }, { width: 15 },
    { width: 15 }, { width: 15 }, { width: 15 },
  ];

  // Status
  const lastRow = 18 + (timesheet.dailyBreakdown?.length || 0);
  sheet.getCell(`A${lastRow}`).value = `Status: ${timesheet.status?.toUpperCase() || 'PENDING'}`;
  sheet.getCell(`A${lastRow + 1}`).value = 'Generated by SiteView — Build Chain';
  sheet.getCell(`A${lastRow + 1}`).font = { italic: true, color: { argb: 'FF888888' } };

  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
}

module.exports = { generateExcel };
