const { db } = require('./firebase');
const { v4: uuidv4 } = require('uuid');

// When a maintenance schedule goes overdue, put an actionable ticket in the
// supervisors' repair-ticket queue (SiteView technical guideline §4.3).
// Deduped: one open auto-ticket per schedule at a time.

async function ensureMaintenanceDueTicket(schedule, { detail, createdByUid } = {}) {
  const existing = await db.collection('repair_tickets')
    .where('scheduleId', '==', schedule.id)
    .get();
  const hasOpen = existing.docs.some(d =>
    ['pending', 'approved', 'in_progress'].includes(d.data().status));
  if (hasOpen) return null;

  const id = uuidv4();
  const now = new Date().toISOString();
  const ticket = {
    id,
    equipmentId: schedule.equipmentId,
    equipmentName: schedule.equipmentName,
    siteId: schedule.siteId,
    priority: 'medium',
    issueType: 'maintenance_due',
    description: `Scheduled ${(schedule.maintenanceType || '').replace(/_/g, ' ')} is overdue${detail ? ` — ${detail}` : ''}`,
    hoursAtReport: null,
    odometerAtReport: null,
    isSafeToOperate: true,
    reportedBy: createdByUid || 'system',
    reportedByName: 'Auto-generated',
    reportedAt: now,
    status: 'pending',
    approvedBy: null,
    approvedAt: null,
    rejectedBy: null,
    rejectedReason: null,
    assignedTo: null,
    estimatedCost: null,
    actualCost: null,
    completedAt: null,
    photos: [],
    comments: [],
    maintenanceRecordId: null,
    scheduleId: schedule.id,
    autoGenerated: true,
  };

  await db.collection('repair_tickets').doc(id).set(ticket);

  await db.collection('audit_logs').doc(uuidv4()).set({
    action: 'MAINTENANCE_TICKET_AUTO_CREATED',
    ticketId: id,
    scheduleId: schedule.id,
    equipmentId: schedule.equipmentId,
    performedBy: createdByUid || 'system',
    timestamp: now,
  });

  return ticket;
}

module.exports = { ensureMaintenanceDueTicket };
