const PDFDocument = require('pdfkit');

async function generatePDF(timesheet) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Header
    doc.fontSize(20).fillColor('#1a237e').text('BUILD CHAIN', { align: 'center' });
    doc.fontSize(14).fillColor('#333').text('SITE VIEW — Timesheet', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(560, doc.y).stroke();
    doc.moveDown();

    // Employee Info
    doc.fontSize(12).fillColor('#000');
    doc.text(`Employee: ${timesheet.employeeName}`);
    doc.text(`Site: ${timesheet.siteId}`);
    doc.text(`Payment Type: ${timesheet.paymentType}`);
    doc.text(`Period: ${timesheet.startDate} to ${timesheet.endDate}`);
    doc.moveDown();

    // Summary
    doc.fontSize(13).fillColor('#1a237e').text('Summary');
    doc.fontSize(11).fillColor('#000');
    doc.text(`Total Hours:    ${timesheet.totalHours} hrs`);
    doc.text(`Break Hours:    ${timesheet.breakHours} hrs`);
    doc.text(`Billable Hours: ${timesheet.billableHours} hrs`);
    doc.text(`Total Pay:      $${timesheet.payAmount}`);
    doc.moveDown();

    // Daily Breakdown
    doc.fontSize(13).fillColor('#1a237e').text('Daily Breakdown');
    doc.moveDown(0.5);

    if (timesheet.dailyBreakdown && timesheet.dailyBreakdown.length > 0) {
      timesheet.dailyBreakdown.forEach(day => {
        doc.fontSize(11).fillColor('#333').text(
          `${day.date}  |  Total: ${day.totalHours}h  |  Break: ${day.breakHours}h  |  Billable: ${day.billableHours}h`
        );
      });
    }

    doc.moveDown();

    // Approval
    doc.moveTo(50, doc.y).lineTo(560, doc.y).stroke();
    doc.moveDown();
    doc.fontSize(10).fillColor('#666');
    doc.text(`Status: ${timesheet.status?.toUpperCase() || 'PENDING'}`);
    if (timesheet.approvedBy) doc.text(`Approved by: ${timesheet.approvedBy} on ${timesheet.approvedAt}`);
    doc.moveDown(2);
    doc.text('Generated by SiteView — Build Chain', { align: 'center' });

    doc.end();
  });
}

module.exports = { generatePDF };
