const PDFDocument = require('pdfkit');

async function generatePDF(timesheet) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Header
    doc.fontSize(20).fillColor('#1a237e').text('BUILD CHAIN', { align: 'center' });
    doc.fontSize(14).fillColor('#333').text('SITE VIEW — Timesheet', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(560, doc.y).stroke();
    doc.moveDown();

    // Employee Info
    doc.fontSize(12).fillColor('#000');
    doc.text(`Employee: ${timesheet.employeeName}`);
    doc.text(`Site: ${timesheet.siteId}`);
    doc.text(`Payment Type: ${timesheet.paymentType}`);
    doc.text(`Period: ${timesheet.startDate} to ${timesheet.endDate}`);
    doc.moveDown();

    // Summary
    doc.fontSize(13).fillColor('#1a237e').text('Summary');
    doc.fontSize(11).fillColor('#000');
    doc.text(`Total Hours:    ${timesheet.totalHours} hrs`);
    doc.text(`Break Hours:    ${timesheet.breakHours} hrs`);
    doc.text(`Billable Hours: ${timesheet.billableHours} hrs`);
    doc.text(`Total Pay:      $${timesheet.payAmount}`);
    doc.moveDown();

    // Daily Breakdown
    doc.fontSize(13).fillColor('#1a237e').text('Daily Breakdown');
    doc.moveDown(0.5);

    if (timesheet.dailyBreakdown && timesheet.dailyBreakdown.length > 0) {
      timesheet.dailyBreakdown.forEach(day => {
        doc.fontSize(11).fillColor('#333').text(
          `${day.date}  |  Total: ${day.totalHours}h  |  Break: ${day.breakHours}h  |  Billable: ${day.billableHours}h`
        );
      });
    }

    doc.moveDown();

    // Approval
    doc.moveTo(50, doc.y).lineTo(560, doc.y).stroke();
    doc.moveDown();
    doc.fontSize(10).fillColor('#666');
    doc.text(`Status: ${timesheet.status?.toUpperCase() || 'PENDING'}`);
    if (timesheet.approvedBy) doc.text(`Approved by: ${timesheet.approvedBy} on ${timesheet.approvedAt}`);
    doc.moveDown(2);
    doc.text('Generated by SiteView — Build Chain', { align: 'center' });

    doc.end();
  });
}

async function generateTMInvoicePDF(invoice) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    doc.fontSize(20).fillColor('#1a237e').text('BUILD CHAIN', { align: 'center' });
    doc.fontSize(14).fillColor('#333').text('SITE VIEW — T&M Invoice', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(560, doc.y).stroke();
    doc.moveDown();

    doc.fontSize(12).fillColor('#000');
    doc.text(`${invoice.title}`);
    doc.text(`Site: ${invoice.siteName}`);
    doc.text(`Period: ${invoice.periodStart} to ${invoice.periodEnd}`);
    doc.text(`Status: ${invoice.status.toUpperCase()}`);
    doc.moveDown();

    function section(name, lines, columns) {
      if (!lines.length) return;
      doc.fontSize(13).fillColor('#1a237e').text(name);
      doc.fontSize(10).fillColor('#333');
      lines.forEach(l => doc.text(columns(l)));
      doc.moveDown(0.5);
    }

    section('Labor', invoice.lineItems.labor,
      l => `${l.employeeName}   ${l.hours} hrs @ $${l.rate}/hr = $${l.cost}`);
    section('Equipment', invoice.lineItems.equipment,
      l => `${l.equipmentName}   ${l.hours} hrs @ $${l.rate}/hr = $${l.cost}`);
    section('Materials', invoice.lineItems.materials,
      l => `${l.description}   ${l.qty} ${l.unit} @ $${l.unitCost} = $${l.cost}`);

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(560, doc.y).stroke();
    doc.moveDown();
    doc.fontSize(11).fillColor('#000');
    doc.text(`Labor Subtotal:      $${invoice.subtotals.labor}`);
    doc.text(`Equipment Subtotal:  $${invoice.subtotals.equipment}`);
    doc.text(`Materials Subtotal:  $${invoice.subtotals.materials}`);
    doc.text(`Subtotal:            $${invoice.subtotal}`);
    if (invoice.markupPercent) doc.text(`Markup (${invoice.markupPercent}%):      $${invoice.markupAmount}`);
    doc.fontSize(13).fillColor('#1a237e').text(`Total Due:           $${invoice.total}`);
    doc.moveDown(2);
    doc.fontSize(10).fillColor('#666').text('Generated by SiteView — Build Chain', { align: 'center' });

    doc.end();
  });
}

module.exports = { generatePDF, generateTMInvoicePDF };
